name: ItemGetOut
version: 1.0.0
main: net.xstudio.itemgetout.main
api-version: 1.15
description: A plugin that allows players to manage item blacklists through GUI and automatically destroys blacklisted items when picked up.

commands:
  itemgetout:
    description: Opens the item blacklist management GUI (Admin)
    usage: /<command>
  blacklist:
    description: Opens the item blacklist management GUI
    usage: /<command>
